import React, { useEffect, useRef, useState } from 'react';
import type { Match } from '../utils/types';
interface MatchCardProps { match: Match; isActive: boolean; onWatch: (id: string | number) => void; onUnwatch: (id: string | number) => void; }
export const MatchCard: React.FC<MatchCardProps> = ({ match, isActive, onWatch, onUnwatch }) => {
  const statusLower = match.status.toLowerCase(); const isLive = statusLower === 'live';
  const [pulse, setPulse] = useState({ home: false, away: false }); const previous = useRef({ home: match.homeScore, away: match.awayScore });
  useEffect(() => { const changed = { home: previous.current.home !== match.homeScore, away: previous.current.away !== match.awayScore }; if (changed.home || changed.away) { setPulse(changed); const timer = setTimeout(() => setPulse({ home: false, away: false }), 900); previous.current = { home: match.homeScore, away: match.awayScore }; return () => clearTimeout(timer); } previous.current = { home: match.homeScore, away: match.awayScore }; }, [match.homeScore, match.awayScore]);
  const label = isLive ? (isActive ? 'Watching Live' : 'Watch Live') : statusLower === 'finished' ? (isActive ? 'Viewing Recap' : 'View Recap') : (isActive ? 'Viewing Match' : 'View Match');
  return <article className={`match-card ${isActive ? 'active' : ''}`}><div className="card-top"><span className="sport-pill">{match.sport}</span><span className="status">{isLive && <i className="live-dot" />}{match.status.charAt(0).toUpperCase() + match.status.slice(1).toLowerCase()}</span></div><div className="team-list"><div className="team-row"><span className="team-name">{match.homeTeam}</span><strong className={`score ${pulse.home ? 'pulse' : ''}`}>{match.homeScore}</strong></div><div className="team-row"><span className="team-name">{match.awayTeam}</span><strong className={`score ${pulse.away ? 'pulse' : ''}`}>{match.awayScore}</strong></div></div><div className="card-footer"><span className="time">{new Date(match.startTime).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}</span><div className="action-row"><button className={`action-btn ${isActive ? 'blue' : ''}`} disabled={isActive} onClick={() => onWatch(match.id)}>{label}</button>{isActive && <button className="action-btn secondary" onClick={() => onUnwatch(match.id)}>Close</button>}</div></div></article>;
};
