import React, { useEffect, useRef, useState } from 'react';
import type { Match } from '../utils/types';
import { formatMatchDate, formatMatchTime, matchStatusLabel } from '../utils/matches';
interface MatchCardProps { match: Match; isActive: boolean; onWatch: (id: string | number) => void; onUnwatch: (id: string | number) => void; }
export const MatchCard: React.FC<MatchCardProps> = ({ match, isActive, onWatch, onUnwatch }) => {
  const statusLower = match.status.toLowerCase(); const isLive = statusLower === 'live';
  const [pulse, setPulse] = useState({ home: false, away: false }); const previous = useRef({ home: match.homeScore, away: match.awayScore });
  useEffect(() => { const changed = { home: previous.current.home !== match.homeScore, away: previous.current.away !== match.awayScore }; if (changed.home || changed.away) { setPulse(changed); const timer = setTimeout(() => setPulse({ home: false, away: false }), 900); previous.current = { home: match.homeScore, away: match.awayScore }; return () => clearTimeout(timer); } previous.current = { home: match.homeScore, away: match.awayScore }; }, [match.homeScore, match.awayScore]);
  const label = isLive ? (isActive ? 'Watching Live' : 'Watch Live') : statusLower === 'finished' ? (isActive ? 'Viewing Recap' : 'View Recap') : (isActive ? 'Viewing Match' : 'View Match');
  return <article className={`flex min-h-[220px] flex-col rounded-[15px] border-2 border-[#171717] bg-white p-5 transition hover:-translate-x-0.5 hover:-translate-y-0.5 hover:shadow-[4px_4px_0_#171717] ${isActive ? 'outline outline-3 outline-offset-2 outline-[#ffdc3e] shadow-[4px_4px_0_#171717]' : ''}`}><div className="mb-5 flex items-center justify-between gap-3"><span className="rounded-full border-2 border-[#aaa] px-2 py-0.5 text-[11px] font-extrabold uppercase">{match.sport}</span><span className="text-[13px] font-bold">{isLive && <i className="mr-1.5 inline-block size-2.5 rounded-full border border-[#171717] bg-[#e7444d]" />}{matchStatusLabel(match.status)}</span></div><div className="grid gap-2.5"><div className="flex items-center justify-between gap-3"><span className="min-w-0 truncate text-[17px] font-extrabold">{match.homeTeam}</span><strong className={`min-w-14 rounded-[10px] border-2 border-[#aaa] bg-[#f2f2f2] px-2 py-1 text-center text-[22px] font-extrabold ${pulse.home ? 'bg-[#ffdc3e]' : ''}`}>{match.homeScore}</strong></div><div className="flex items-center justify-between gap-3"><span className="min-w-0 truncate text-[17px] font-extrabold">{match.awayTeam}</span><strong className={`min-w-14 rounded-[10px] border-2 border-[#aaa] bg-[#f2f2f2] px-2 py-1 text-center text-[22px] font-extrabold ${pulse.away ? 'bg-[#ffdc3e]' : ''}`}>{match.awayScore}</strong></div></div><div className="mt-auto flex items-center justify-between gap-3 border-t border-dashed border-[#ddd] pt-4"><div className="mono flex flex-col gap-1 text-[11px] text-[#555]" aria-label={`Match date ${formatMatchDate(match.startTime)}, start time ${formatMatchTime(match.startTime)}, end time ${formatMatchTime(match.endTime)}`}><span><strong>Date:</strong> {formatMatchDate(match.startTime)}</span><span><strong>Start:</strong> {formatMatchTime(match.startTime)}</span><span><strong>End:</strong> {formatMatchTime(match.endTime)}</span></div><div className="flex gap-2"><button className={`rounded-full border-2 border-[#171717] bg-[#ffdc3e] px-3.5 py-2 text-xs font-extrabold hover:brightness-95 disabled:cursor-default disabled:opacity-50 ${isActive ? 'bg-[#a9dff7]' : ''}`} disabled={isActive} onClick={() => onWatch(match.id)}>{label}</button>{isActive && <button className="rounded-full border-2 border-[#171717] bg-white px-3 py-2 text-xs font-extrabold" onClick={() => onUnwatch(match.id)}>Close</button>}</div></div></article>;
};
